window.BILIBILI_DATA = {
  "summary": {
    "total_fans": "191",
    "total_views": "6.73万",
    "total_videos": 62,
    "total_likes": "1405",
    "last_month_views": "3148",
    "last_month_views_change": "-73.2%",
    "last_month_videos": 6,
    "last_month_videos_change": "-7",
    "last_month_likes": "171",
    "last_month_likes_change": "-47.4%"
  },
  "trend_chart": {
    "labels": [
      "2023.02",
      "2023.07",
      "2023.08",
      "2023.10",
      "2024.02",
      "2024.07",
      "2024.08",
      "2024.09",
      "2024.12",
      "2025.03",
      "2025.04",
      "2025.05",
      "2025.06",
      "2025.07",
      "2025.08",
      "2025.09"
    ],
    "datasets": [
      {
        "label": "累计视频发布数",
        "data": [
          1,
          3,
          4,
          5,
          6,
          7,
          9,
          10,
          13,
          17,
          24,
          31,
          34,
          43,
          56,
          62
        ]
      },
      {
        "label": "累计播放量",
        "data": [
          146,
          704,
          1095,
          1154,
          1454,
          1691,
          6708,
          6955,
          7868,
          8322,
          36116,
          40286,
          41210,
          52413,
          64158,
          67306
        ]
      },
      {
        "label": "累计点赞量",
        "data": [
          8,
          32,
          49,
          52,
          62,
          78,
          205,
          210,
          242,
          267,
          631,
          687,
          715,
          909,
          1234,
          1405
        ]
      },
      {
        "label": "每月视频发布数",
        "data": [
          1,
          2,
          1,
          1,
          1,
          1,
          2,
          1,
          3,
          4,
          7,
          7,
          3,
          9,
          13,
          6
        ]
      },
      {
        "label": "每月播放量",
        "data": [
          146,
          558,
          391,
          59,
          300,
          237,
          5017,
          247,
          913,
          454,
          27794,
          4170,
          924,
          11203,
          11745,
          3148
        ]
      },
      {
        "label": "每月点赞量",
        "data": [
          8,
          24,
          17,
          3,
          10,
          16,
          127,
          5,
          32,
          25,
          364,
          56,
          28,
          194,
          325,
          171
        ]
      }
    ]
  },
  "video_performance": [
    {
      "title": "四号逃生舱の诞生.mp4",
      "views": 23991,
      "likes": 298,
      "like_rate": 1.2421324663415447
    }
  ],
  "monthly_details": {
    "2023-02": {
      "videos": 1,
      "views": 146,
      "likes": 8
    },
    "2023-07": {
      "videos": 2,
      "views": 558,
      "likes": 24
    },
    "2023-08": {
      "videos": 1,
      "views": 391,
      "likes": 17
    },
    "2023-10": {
      "videos": 1,
      "views": 59,
      "likes": 3
    },
    "2024-02": {
      "videos": 1,
      "views": 300,
      "likes": 10
    },
    "2024-07": {
      "videos": 1,
      "views": 237,
      "likes": 16
    },
    "2024-08": {
      "videos": 2,
      "views": 5017,
      "likes": 127
    },
    "2024-09": {
      "videos": 1,
      "views": 247,
      "likes": 5
    },
    "2024-12": {
      "videos": 3,
      "views": 913,
      "likes": 32
    },
    "2025-03": {
      "videos": 4,
      "views": 454,
      "likes": 25
    },
    "2025-04": {
      "videos": 7,
      "views": 27794,
      "likes": 364
    },
    "2025-05": {
      "videos": 7,
      "views": 4170,
      "likes": 56
    },
    "2025-06": {
      "videos": 3,
      "views": 924,
      "likes": 28
    },
    "2025-07": {
      "videos": 9,
      "views": 11203,
      "likes": 194
    },
    "2025-08": {
      "videos": 13,
      "views": 11745,
      "likes": 325
    },
    "2025-09": {
      "videos": 6,
      "views": 3148,
      "likes": 171
    }
  },
  "follower_chart": {
    "labels": [
      "2022年",
      "2023年",
      "2024年",
      "2025年"
    ],
    "datasets": [
      {
        "label": "B站粉丝数量",
        "data": [
          161,
          171,
          181,
          191
        ]
      }
    ]
  },
  "all_videos": [
    {
      "title": "随意の死",
      "link": "https://www.bilibili.com/video/BV1KM411e7Uh",
      "duration": "0:52",
      "publish_time": "2023-02-11 16:36:54",
      "view_count": 146,
      "like_count": 8,
      "danmaku_count": 1,
      "comment_count": 5,
      "description": "只因限模式随意の死",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "花雨庭这是怎么了？",
      "link": "https://www.bilibili.com/video/BV1ox4y1o7By",
      "duration": "0:52",
      "publish_time": "2023-07-16 07:28:58",
      "view_count": 259,
      "like_count": 12,
      "danmaku_count": 0,
      "comment_count": 5,
      "description": "花雨庭这是抽风了吗?",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "终于 会telly的人又多了一个",
      "link": "https://www.bilibili.com/video/BV1Dc411c78m",
      "duration": "2:09",
      "publish_time": "2023-07-21 16:05:10",
      "view_count": 299,
      "like_count": 12,
      "danmaku_count": 1,
      "comment_count": 9,
      "description": "",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "当我在花雨庭遇到挂机的人时♂",
      "link": "https://www.bilibili.com/video/BV1Jh4y1F7Rp",
      "duration": "5:18",
      "publish_time": "2023-08-08 17:13:06",
      "view_count": 391,
      "like_count": 17,
      "danmaku_count": 17,
      "comment_count": 9,
      "description": "O.o\n他最后还是很新的把我打到虚空里面了",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "显卡:我点个陪玩怎么了？",
      "link": "https://www.bilibili.com/video/BV1tC4y1G7m8",
      "duration": "0:09",
      "publish_time": "2023-10-13 22:32:00",
      "view_count": 59,
      "like_count": 3,
      "danmaku_count": 0,
      "comment_count": 2,
      "description": "吕布骑狗",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "在不知不觉中 似乎已经有了肌肉记忆了",
      "link": "https://www.bilibili.com/video/BV1Z7421P7yg",
      "duration": "0:16",
      "publish_time": "2024-02-05 10:22:37",
      "view_count": 300,
      "like_count": 10,
      "danmaku_count": 0,
      "comment_count": 2,
      "description": "我很懒",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "人生中第一次几乎满telly过去",
      "link": "https://www.bilibili.com/video/BV12Hb9ebEbC",
      "duration": "0:20",
      "publish_time": "2024-07-15 18:56:46",
      "view_count": 237,
      "like_count": 16,
      "danmaku_count": 1,
      "comment_count": 11,
      "description": "第一次奥\n某腐竹不去好好开服在这里练习搭路没被成员发现 望众知",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "我的世界物品展示插件[Liteitemshow]",
      "link": "https://www.bilibili.com/video/BV1PunZe1EKV",
      "duration": "5:04",
      "publish_time": "2024-08-31 16:31:59",
      "view_count": 1463,
      "like_count": 17,
      "danmaku_count": 0,
      "comment_count": 7,
      "description": "Github开源地址github.com/Little_100/Liteitemshow",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "Minecraft但是玩家之间教培(",
      "link": "https://www.bilibili.com/video/BV1zXebefEzQ",
      "duration": "2:27",
      "publish_time": "2024-08-15 17:09:10",
      "view_count": 3554,
      "like_count": 110,
      "danmaku_count": 2,
      "comment_count": 7,
      "description": "美丽的简介\n\n开源地址 Little100/Minecraft_Fuck_Plugin (github.com)\n下载地址 Release Releases v1.0 · Little100/Minecraft_Fuck_Plugin (github.com) 点击那个.jar结尾的文件就可以",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "《10KMbps峰值上传》",
      "link": "https://www.bilibili.com/video/BV1TVtaeaEJG",
      "duration": "0:42",
      "publish_time": "2024-09-17 14:57:40",
      "view_count": 247,
      "like_count": 5,
      "danmaku_count": 0,
      "comment_count": 3,
      "description": "不知道为什么 能跑那么高就挺神奇的 我寻思hosts我也没改啊",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "老E5的跑图能力放到现在来看也是十分超前...",
      "link": "https://www.bilibili.com/video/BV1D2q5YtEeV",
      "duration": "3:25",
      "publish_time": "2024-12-08 00:56:30",
      "view_count": 323,
      "like_count": 15,
      "danmaku_count": 0,
      "comment_count": 5,
      "description": "E!5!",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "撸 猫",
      "link": "https://www.bilibili.com/video/BV1JciUYPEAK",
      "duration": "0:30",
      "publish_time": "2024-12-04 22:53:49",
      "view_count": 432,
      "like_count": 10,
      "danmaku_count": 1,
      "comment_count": 4,
      "description": "我 爱 撸 猫(物理意义上)",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "[我的世界]铁砧修复等插件",
      "link": "https://www.bilibili.com/video/BV1cWz4YSENz",
      "duration": "8:02",
      "publish_time": "2024-12-01 14:21:09",
      "view_count": 158,
      "like_count": 7,
      "danmaku_count": 2,
      "comment_count": 4,
      "description": "声音不好听也是没办法...\n插件呢都是根据自己需求写的，如果能帮到某些人的话就将就的用吧，写的也挺烂的...\n毕竟高二了没时间写 两周一次回家也挺难受\n后续的话可能会继续完善一下插件，也请有问题/建议提issue\n友情链接:\nGithub搜Little_100\n我的服务器官网(预览版)www.gaymc.top\n直播号(压根没正经直播过)@Little_100_",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "荆棘III的正确用法",
      "link": "https://www.bilibili.com/video/BV1zoZPYYEsb",
      "duration": "2:49",
      "publish_time": "2025-03-27 01:43:11",
      "view_count": 251,
      "like_count": 10,
      "danmaku_count": 1,
      "comment_count": 6,
      "description": "美丽的简介",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "3秒急速下播(物理意义上)",
      "link": "https://www.bilibili.com/video/BV1Tj99YgEmY",
      "duration": "0:06",
      "publish_time": "2025-03-08 14:15:00",
      "view_count": 32,
      "like_count": 5,
      "danmaku_count": 0,
      "comment_count": 2,
      "description": "冬夏玛德法克",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "《因为太抽象了所以一秒也不用剪》",
      "link": "https://www.bilibili.com/video/BV1U8oqYTEBH",
      "duration": "19:05",
      "publish_time": "2025-03-24 01:10:55",
      "view_count": 54,
      "like_count": 3,
      "danmaku_count": 0,
      "comment_count": 0,
      "description": "美丽的简介",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "重生之我那爱玩星铁的朋友",
      "link": "https://www.bilibili.com/video/BV1tQ9bYuEet",
      "duration": "6:52",
      "publish_time": "2025-03-02 23:32:15",
      "view_count": 117,
      "like_count": 7,
      "danmaku_count": 1,
      "comment_count": 3,
      "description": "美丽的简介",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "肺雾烟花号.mp4",
      "link": "https://www.bilibili.com/video/BV1ftGCzKEyV",
      "duration": "1:26",
      "publish_time": "2025-04-29 15:10:40",
      "view_count": 248,
      "like_count": 6,
      "danmaku_count": 0,
      "comment_count": 0,
      "description": "迫害阳光号.exe",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "4546B之Bug传奇",
      "link": "https://www.bilibili.com/video/BV1wvGQzeEYD",
      "duration": "5:54",
      "publish_time": "2025-04-30 13:57:19",
      "view_count": 1151,
      "like_count": 24,
      "danmaku_count": 2,
      "comment_count": 7,
      "description": "我要飞的更高",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "极光号炸了两次.mp4",
      "link": "https://www.bilibili.com/video/BV1fVLgzEEG1",
      "duration": "0:51",
      "publish_time": "2025-04-21 12:43:16",
      "view_count": 1813,
      "like_count": 18,
      "danmaku_count": 2,
      "comment_count": 3,
      "description": "美丽的简介",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "缠怨藤有粘液块的属性？",
      "link": "https://www.bilibili.com/video/BV194dcYzEVM",
      "duration": "0:43",
      "publish_time": "2025-04-06 12:08:59",
      "view_count": 152,
      "like_count": 6,
      "danmaku_count": 0,
      "comment_count": 4,
      "description": "玩的时候发现的",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "[Raw_Block_Smelting]我的世界可以把粗矿物快熔炼为金属块的插件",
      "link": "https://www.bilibili.com/video/BV1aSRzY5EQp",
      "duration": "1:41",
      "publish_time": "2025-04-06 22:37:48",
      "view_count": 212,
      "like_count": 5,
      "danmaku_count": 0,
      "comment_count": 5,
      "description": "美丽的简介",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "[MC]纯插件实现的炼金术士袋子",
      "link": "https://www.bilibili.com/video/BV1YQRrYDEYq",
      "duration": "5:22",
      "publish_time": "2025-04-07 02:05:58",
      "view_count": 227,
      "like_count": 7,
      "danmaku_count": 0,
      "comment_count": 4,
      "description": "美丽的简介",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "四号逃生舱の诞生.mp4",
      "link": "https://www.bilibili.com/video/BV1t5LRz4Es8",
      "duration": "0:47",
      "publish_time": "2025-04-26 18:51:43",
      "view_count": 23991,
      "like_count": 298,
      "danmaku_count": 11,
      "comment_count": 50,
      "description": "美丽捏",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "能在这种情况下telly过去的也是神人了👍",
      "link": "https://www.bilibili.com/video/BV1nHJnztEbL",
      "duration": "2:48",
      "publish_time": "2025-05-22 15:26:55",
      "view_count": 562,
      "like_count": 10,
      "danmaku_count": 0,
      "comment_count": 13,
      "description": "卡顿问题还是没解决\n根本玩不了一点",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "[我的世界]如何在联机问题网页添加自己的贡献",
      "link": "https://www.bilibili.com/video/BV1CzJgzNE3V",
      "duration": "6:14",
      "publish_time": "2025-05-18 10:55:42",
      "view_count": 142,
      "like_count": 8,
      "danmaku_count": 0,
      "comment_count": 5,
      "description": "多多贡献自己的力量..",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "图片转我的世界皮肤[未完成]",
      "link": "https://www.bilibili.com/video/BV1yaVAzNE7n",
      "duration": "2:13",
      "publish_time": "2025-05-04 14:41:45",
      "view_count": 391,
      "like_count": 8,
      "danmaku_count": 0,
      "comment_count": 7,
      "description": "开源地址https://github.com/Little100/MC_Skin_Generator",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "[我的世界]多人联机出错了？看看这个网站吧！",
      "link": "https://www.bilibili.com/video/BV1HGJNzEEMo",
      "duration": "4:16",
      "publish_time": "2025-05-17 22:57:43",
      "view_count": 133,
      "like_count": 8,
      "danmaku_count": 0,
      "comment_count": 9,
      "description": "希望大家多多提交issue或者贡献一份属于自己的力量\nhttps://www.100moi.top",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "137k无敌暴雷体制",
      "link": "https://www.bilibili.com/video/BV1a3ECzzEsA",
      "duration": "1:18",
      "publish_time": "2025-05-15 09:45:47",
      "view_count": 280,
      "like_count": 5,
      "danmaku_count": 2,
      "comment_count": 8,
      "description": "这体制也算是烂透了",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "踩奶毛毛怪怪可爱捏",
      "link": "https://www.bilibili.com/video/BV1AiEsz6Eab",
      "duration": "0:32",
      "publish_time": "2025-05-16 16:32:30",
      "view_count": 395,
      "like_count": 4,
      "danmaku_count": 0,
      "comment_count": 3,
      "description": "可爱捏",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "求助,我的我的世界间隙性卡顿",
      "link": "https://www.bilibili.com/video/BV1k9JzzEE7z",
      "duration": "0:52",
      "publish_time": "2025-05-22 00:10:06",
      "view_count": 2267,
      "like_count": 13,
      "danmaku_count": 0,
      "comment_count": 34,
      "description": "看左上角第二个帧数 视频内出现的算少 正常玩更容易出现 基本上属于玩不了pvp的情况 也不清楚是啥问题来求助了 各种硬件占用都挺正常 感觉跟我这缩肛的cpu有点关系",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "Windows美化.exe",
      "link": "https://www.bilibili.com/video/BV1GmMCzUEF3",
      "duration": "1:47",
      "publish_time": "2025-06-14 10:27:21",
      "view_count": 403,
      "like_count": 16,
      "danmaku_count": 0,
      "comment_count": 7,
      "description": "Windows开始菜单美化是根据BV1kzEwzuESt的教程来的 原文内容如下:\n\"\n所用部分json:\n{\n\"controlStyles[0].target\": \"Border#AcrylicOverlay\",\n\"controlStyles[0].styles[0]\": \"Background:=<ImageBrush Stretch=\\\"UniformToFill\\\" ImageSource=\\\"D:\\\\Program Files\\\\Windhawk\\\\image.jpg\\\" Opacity=\\\"0.65\\\" />\"\n}\n完整内容见专栏:https://www.bilibili.com/opus/1066492091022966805\n\"\n其中ImageSource=必须用https的url或者是必须在windhawk安装根目录中的图片 我自己确定能够用的格式有jpg png gif webp(没动态)\n其他的是根据windhawk模组中自带的默认样式选择的\n窗口开关闭的效果是WindoFX的 配置如下\nOpen: Expand from - Multiple Styles | ",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "B站个人视频分析工具",
      "link": "https://www.bilibili.com/video/BV1yRKmzkEcF",
      "duration": "2:54",
      "publish_time": "2025-06-28 22:25:32",
      "view_count": 162,
      "like_count": 5,
      "danmaku_count": 0,
      "comment_count": 5,
      "description": "github\nLittle100/Video_Data_Analysis",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "真的猫尾巴.mp4",
      "link": "https://www.bilibili.com/video/BV14oMCzkEok",
      "duration": "0:15",
      "publish_time": "2025-06-14 10:17:08",
      "view_count": 359,
      "like_count": 7,
      "danmaku_count": 0,
      "comment_count": 5,
      "description": "喵喵喵 不是插件也不是挂件 是真的猫尾巴",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "等价交换插件0.1.2",
      "link": "https://www.bilibili.com/video/BV1qG8HzUE25",
      "duration": "4:58",
      "publish_time": "2025-07-28 22:40:24",
      "view_count": 510,
      "like_count": 12,
      "danmaku_count": 0,
      "comment_count": 5,
      "description": "美丽的简介~",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "我的世界材质包1.21.4+ custom model data为同种物品上不同的材质的方法",
      "link": "https://www.bilibili.com/video/BV1Ue8dzaEKG",
      "duration": "6:15",
      "publish_time": "2025-07-29 23:04:16",
      "view_count": 575,
      "like_count": 15,
      "danmaku_count": 0,
      "comment_count": 12,
      "description": "Null",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "等价交换插件——贤者之石部分功能还原",
      "link": "https://www.bilibili.com/video/BV15f8Hz7E1L",
      "duration": "1:54",
      "publish_time": "2025-07-29 05:20:56",
      "view_count": 432,
      "like_count": 6,
      "danmaku_count": 0,
      "comment_count": 6,
      "description": "阿啊MBBS怎么审核的那么man！\n美丽的简介",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "最新力作:插件版等价交换[待完成]",
      "link": "https://www.bilibili.com/video/BV1C38tzCEqu",
      "duration": "3:09",
      "publish_time": "2025-07-26 17:23:22",
      "view_count": 1059,
      "like_count": 12,
      "danmaku_count": 0,
      "comment_count": 14,
      "description": "美丽的简介",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "等价交换插件测试版发布",
      "link": "https://www.bilibili.com/video/BV1of8GzxET6",
      "duration": "8:53",
      "publish_time": "2025-07-27 23:47:25",
      "view_count": 6071,
      "like_count": 81,
      "danmaku_count": 7,
      "comment_count": 43,
      "description": "神秘链接\n原创 - 开源 - 娱乐 - 经济 - 等价交换插件版 | MineBBS 我的世界中文论坛\nLittle100/ProjectE-插件 --- Little100/ProjectE-plugin",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "最新力作!",
      "link": "https://www.bilibili.com/video/BV1EPGJzvEN3",
      "duration": "0:57",
      "publish_time": "2025-07-08 11:02:28",
      "view_count": 796,
      "like_count": 15,
      "danmaku_count": 0,
      "comment_count": 9,
      "description": "《基于原版的终极堆叠》",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "[插件]我的世界加速火把插件",
      "link": "https://www.bilibili.com/video/BV1yV32zJEH6",
      "duration": "2:35",
      "publish_time": "2025-07-07 23:47:18",
      "view_count": 657,
      "like_count": 15,
      "danmaku_count": 0,
      "comment_count": 1,
      "description": "美丽捏\n可惜农作物不支持",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "最会写插件的一集",
      "link": "https://www.bilibili.com/video/BV1i832zBETv",
      "duration": "1:23",
      "publish_time": "2025-07-07 22:44:20",
      "view_count": 406,
      "like_count": 6,
      "danmaku_count": 1,
      "comment_count": 8,
      "description": "美丽呢",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "女装？",
      "link": "https://www.bilibili.com/video/BV1MJuJzyEeK",
      "duration": "0:38",
      "publish_time": "2025-07-15 17:10:50",
      "view_count": 697,
      "like_count": 32,
      "danmaku_count": 2,
      "comment_count": 14,
      "description": "不好看的简介",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "插件中指令的内容讲解",
      "link": "https://www.bilibili.com/video/BV1tRh6zdEcq",
      "duration": "5:40",
      "publish_time": "2025-08-31 02:27:52",
      "view_count": 249,
      "like_count": 16,
      "danmaku_count": 0,
      "comment_count": 4,
      "description": "简介好看不",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "配置文件内容介绍&修改",
      "link": "https://www.bilibili.com/video/BV1URh6zdE5i",
      "duration": "6:33",
      "publish_time": "2025-08-31 02:27:46",
      "view_count": 518,
      "like_count": 21,
      "danmaku_count": 0,
      "comment_count": 5,
      "description": "简介有鬼",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "等价交换插件最后一个测试版！",
      "link": "https://www.bilibili.com/video/BV1QZhvzEE1F",
      "duration": "3:52",
      "publish_time": "2025-08-30 12:43:13",
      "view_count": 994,
      "like_count": 32,
      "danmaku_count": 1,
      "comment_count": 9,
      "description": "这个入很懒",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "等价交换插件版正式版预备发布...",
      "link": "https://www.bilibili.com/video/BV1pUejzWE7S",
      "duration": "2:18",
      "publish_time": "2025-08-24 14:39:16",
      "view_count": 1613,
      "like_count": 55,
      "danmaku_count": 0,
      "comment_count": 26,
      "description": "别问为什么没声音 因为快开学了母亲来旁边唠叨个不停",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "我的世界等价交换插件版0.2.1",
      "link": "https://www.bilibili.com/video/BV1eBYDzNEsf",
      "duration": "3:44",
      "publish_time": "2025-08-21 11:59:14",
      "view_count": 638,
      "like_count": 22,
      "danmaku_count": 0,
      "comment_count": 7,
      "description": "抱歉Geyser兼容基岩用户可能是做不到了 太难做了",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "我的世界等价交换插件0.2发布",
      "link": "https://www.bilibili.com/video/BV1CttZz4EDG",
      "duration": "4:22",
      "publish_time": "2025-08-12 22:53:40",
      "view_count": 887,
      "like_count": 25,
      "danmaku_count": 0,
      "comment_count": 13,
      "description": "是的 无人在意 这个插件也不会有人用T_T",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "如何快速获取到4546B的矿物资源？",
      "link": "https://www.bilibili.com/video/BV1kfe3z3EQ6",
      "duration": "2:57",
      "publish_time": "2025-08-21 00:51:08",
      "view_count": 1098,
      "like_count": 13,
      "danmaku_count": 1,
      "comment_count": 16,
      "description": "这我还回什么家？！",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "五号逃生舱之未供能工作台",
      "link": "https://www.bilibili.com/video/BV1cFhZztEGd",
      "duration": "0:40",
      "publish_time": "2025-08-30 00:45:38",
      "view_count": 344,
      "like_count": 6,
      "danmaku_count": 1,
      "comment_count": 4,
      "description": "不想让我活别整这死出。",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "我的世界等价交换插件0.2版本马上更新",
      "link": "https://www.bilibili.com/video/BV1Smb5zmEms",
      "duration": "5:23",
      "publish_time": "2025-08-11 19:33:03",
      "view_count": 834,
      "like_count": 24,
      "danmaku_count": 0,
      "comment_count": 27,
      "description": "yeppy",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "前言与如何安装插件",
      "link": "https://www.bilibili.com/video/BV18Dh6zbETt",
      "duration": "6:47",
      "publish_time": "2025-08-31 02:25:19",
      "view_count": 1247,
      "like_count": 27,
      "danmaku_count": 0,
      "comment_count": 8,
      "description": "说了一点屁话就当我放了个屁吧\n开源",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "等价交换插件开发日志...",
      "link": "https://www.bilibili.com/video/BV1MGtkzpEj7",
      "duration": "2:11",
      "publish_time": "2025-08-08 06:25:53",
      "view_count": 503,
      "like_count": 22,
      "danmaku_count": 0,
      "comment_count": 4,
      "description": "bing搜索关键字 projecte plugin github或者直接搜我的名字可能也可以(?)\n分区投错了。。。发现的时候不能改了。。不过无所谓了",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "[我的世界]等价交换插件 现在有了更多的等价交换的煤炭了..",
      "link": "https://www.bilibili.com/video/BV1iWtVzHENk",
      "duration": "3:13",
      "publish_time": "2025-08-05 01:00:37",
      "view_count": 2431,
      "like_count": 51,
      "danmaku_count": 0,
      "comment_count": 11,
      "description": "美丽的简介\n我可能有点4了",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "我的世界等价交换插件0.2版本...[暂未推送]",
      "link": "https://www.bilibili.com/video/BV1YhtmzyEnt",
      "duration": "2:02",
      "publish_time": "2025-08-08 18:58:18",
      "view_count": 389,
      "like_count": 11,
      "danmaku_count": 0,
      "comment_count": 3,
      "description": "hum?",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "超级棍木剑插件发布",
      "link": "https://www.bilibili.com/video/BV15NY3zxEqm",
      "duration": "2:37",
      "publish_time": "2025-09-07 11:33:22",
      "view_count": 248,
      "like_count": 9,
      "danmaku_count": 0,
      "comment_count": 4,
      "description": "棍木",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "█ ͇͇͇͇͇͇̿̿̿̿ ͇͇͇̿̿ ̿̿̿̿̿̿̿̿̿̿̿̿̿̿̿̿̿̿世界. ͇͇͇͇͇̿̿̿exe ͇͇͇͇͇̿̿█停止运行",
      "link": "https://www.bilibili.com/video/BV1mbYLzsEfa",
      "duration": "1:05",
      "publish_time": "2025-09-07 16:22:52",
      "view_count": 878,
      "like_count": 121,
      "danmaku_count": 1,
      "comment_count": 26,
      "description": "",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "等价交换插件支持搜索",
      "link": "https://www.bilibili.com/video/BV1MWp7zgEXm",
      "duration": "1:51",
      "publish_time": "2025-09-13 16:16:07",
      "view_count": 143,
      "like_count": 11,
      "danmaku_count": 0,
      "comment_count": 0,
      "description": "这智能生成的封面笑死我了",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "神秘bug之CMD仅服务器贴图不显示",
      "link": "https://www.bilibili.com/video/BV1neY3zvEpU",
      "duration": "2:46",
      "publish_time": "2025-09-07 10:13:30",
      "view_count": 368,
      "like_count": 6,
      "danmaku_count": 0,
      "comment_count": 1,
      "description": "啊我草这mojang怎么那么坏",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "锄头不再是没用的工具了——超级农事",
      "link": "https://www.bilibili.com/video/BV1XZYLzeE7Q",
      "duration": "4:33",
      "publish_time": "2025-09-08 01:17:16",
      "view_count": 493,
      "like_count": 12,
      "danmaku_count": 0,
      "comment_count": 3,
      "description": "yeppy",
      "fan_growth": "无法获取",
      "danmakus": []
    },
    {
      "title": "等价交换插件版物品介绍",
      "link": "https://www.bilibili.com/video/BV1PBp9ziEQc",
      "duration": "8:55",
      "publish_time": "2025-09-20 22:16:00",
      "view_count": 1018,
      "like_count": 12,
      "danmaku_count": 0,
      "comment_count": 10,
      "description": "美味的简介",
      "fan_growth": "无法获取",
      "danmakus": []
    }
  ],
  "all_danmakus": []
};