window.GITHUB_DATA = {
  "projects": [
    {
      "name": "Web_Myself",
      "fullName": "Little100/Web_Myself",
      "description": "暂无描述",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Web_Myself",
      "updatedAt": "2025-10-05T16:59:28Z",
      "createdAt": "2025-09-06T14:20:55Z",
      "topics": []
    },
    {
      "name": "ProjectE-plugin",
      "fullName": "Little100/ProjectE-plugin",
      "description": "A Minecraft Plugin,from ProjectE mod",
      "language": "Java",
      "stars": 13,
      "forks": 6,
      "url": "https://github.com/Little100/ProjectE-plugin",
      "updatedAt": "2025-10-05T16:31:39Z",
      "createdAt": "2025-07-27T11:20:55Z",
      "topics": [
        "minecraft",
        "minecraft-datapack",
        "minecraft-plugin",
        "minecraft-server",
        "projecte"
      ]
    },
    {
      "name": "Minecraft_Online_Issues",
      "fullName": "Little100/Minecraft_Online_Issues",
      "description": "MOL 帮助玩家解决联机的疑难杂症",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Minecraft_Online_Issues",
      "updatedAt": "2025-10-05T01:52:43Z",
      "createdAt": "2025-05-16T11:53:06Z",
      "topics": []
    },
    {
      "name": "Avaritia_Plugin",
      "fullName": "Little100/Avaritia_Plugin",
      "description": "a simple plugin just from avaitia mod to plugin",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Avaritia_Plugin",
      "updatedAt": "2025-10-04T19:38:24Z",
      "createdAt": "2025-10-04T19:19:59Z",
      "topics": []
    },
    {
      "name": "docs",
      "fullName": "Little100/docs",
      "description": "docs",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/docs",
      "updatedAt": "2025-10-04T19:04:25Z",
      "createdAt": "2025-09-07T18:36:38Z",
      "topics": []
    },
    {
      "name": "Super_Farming",
      "fullName": "Little100/Super_Farming",
      "description": "a minecraft plugin ",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Super_Farming",
      "updatedAt": "2025-09-20T17:34:56Z",
      "createdAt": "2025-09-07T16:39:44Z",
      "topics": [
        "minecraft",
        "minecraft-plugin"
      ]
    },
    {
      "name": "Super_Stick_Sword",
      "fullName": "Little100/Super_Stick_Sword",
      "description": "A Minecraft Plugin,from Super Stick Sword mod",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Super_Stick_Sword",
      "updatedAt": "2025-09-07T18:44:30Z",
      "createdAt": "2025-09-07T03:03:33Z",
      "topics": [
        "minecraft",
        "minecraft-plugin"
      ]
    },
    {
      "name": "MinecraftServersideBlockPack",
      "fullName": "Little100/MinecraftServersideBlockPack",
      "description": "一个可以在我的世界服务端显示方块贴图的方法",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/MinecraftServersideBlockPack",
      "updatedAt": "2025-08-11T13:00:38Z",
      "createdAt": "2025-08-11T12:57:37Z",
      "topics": []
    },
    {
      "name": "Anti-Recall-OneBot",
      "fullName": "Little100/Anti-Recall-OneBot",
      "description": "a normal antirecall",
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Anti-Recall-OneBot",
      "updatedAt": "2025-07-25T19:49:38Z",
      "createdAt": "2025-07-25T19:42:47Z",
      "topics": []
    },
    {
      "name": "Other_Clear_Lag",
      "fullName": "Little100/Other_Clear_Lag",
      "description": "another minecraft clearlag plugin",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Other_Clear_Lag",
      "updatedAt": "2025-07-16T07:36:56Z",
      "createdAt": "2025-07-16T07:36:10Z",
      "topics": []
    },
    {
      "name": "Torcherino_Plugin",
      "fullName": "Little100/Torcherino_Plugin",
      "description": "我的世界加速火把 但是插件版",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Torcherino_Plugin",
      "updatedAt": "2025-07-07T15:51:40Z",
      "createdAt": "2025-07-07T15:49:57Z",
      "topics": []
    },
    {
      "name": "yayagongyi",
      "fullName": "Little100/yayagongyi",
      "description": "吖吖公益",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/yayagongyi",
      "updatedAt": "2025-07-06T08:34:58Z",
      "createdAt": "2025-04-19T02:18:12Z",
      "topics": []
    },
    {
      "name": "Video_Data_Analysis",
      "fullName": "Little100/Video_Data_Analysis",
      "description": "一个简单的分析视频平台的工具",
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Video_Data_Analysis",
      "updatedAt": "2025-06-29T02:05:52Z",
      "createdAt": "2025-06-28T12:50:02Z",
      "topics": []
    },
    {
      "name": "Furry.Beer",
      "fullName": "Little100/Furry.Beer",
      "description": "a furry html",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Furry.Beer",
      "updatedAt": "2025-06-27T17:19:40Z",
      "createdAt": "2025-06-27T17:16:21Z",
      "topics": [
        "furry"
      ]
    },
    {
      "name": "Minecraft_Server_Manager",
      "fullName": "Little100/Minecraft_Server_Manager",
      "description": "a minecraft server mananger",
      "language": "JavaScript",
      "stars": 1,
      "forks": 0,
      "url": "https://github.com/Little100/Minecraft_Server_Manager",
      "updatedAt": "2025-05-20T10:39:16Z",
      "createdAt": "2025-01-22T09:39:23Z",
      "topics": []
    },
    {
      "name": "MC_Skin_Generator",
      "fullName": "Little100/MC_Skin_Generator",
      "description": "Form a image to Minecaft skin",
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/MC_Skin_Generator",
      "updatedAt": "2025-05-04T06:34:27Z",
      "createdAt": "2025-05-04T06:33:05Z",
      "topics": []
    },
    {
      "name": "No_Eat_Limit",
      "fullName": "Little100/No_Eat_Limit",
      "description": "让玩家没有吃食物的饱食度限制",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/No_Eat_Limit",
      "updatedAt": "2025-04-13T08:41:43Z",
      "createdAt": "2025-04-13T08:37:31Z",
      "topics": []
    },
    {
      "name": "Alchemical_Bag_Plugin",
      "fullName": "Little100/Alchemical_Bag_Plugin",
      "description": "炼金术袋子 但是是插件版",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Alchemical_Bag_Plugin",
      "updatedAt": "2025-04-08T12:01:50Z",
      "createdAt": "2025-04-06T18:01:24Z",
      "topics": []
    },
    {
      "name": "Raw_Block_Smelting",
      "fullName": "Little100/Raw_Block_Smelting",
      "description": "Allows smelting raw ore blocks into metal blocks.",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Raw_Block_Smelting",
      "updatedAt": "2025-04-06T14:31:19Z",
      "createdAt": "2025-04-06T14:30:32Z",
      "topics": []
    },
    {
      "name": "GayMCPack",
      "fullName": "Little100/GayMCPack",
      "description": "a minecraft pack",
      "language": null,
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/GayMCPack",
      "updatedAt": "2025-04-06T10:13:53Z",
      "createdAt": "2024-08-19T14:52:11Z",
      "topics": []
    },
    {
      "name": ".love_domain",
      "fullName": "Little100/.love_domain",
      "description": "暂无描述",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/.love_domain",
      "updatedAt": "2025-03-15T11:55:48Z",
      "createdAt": "2025-02-11T08:08:17Z",
      "topics": []
    },
    {
      "name": "Little100",
      "fullName": "Little100/Little100",
      "description": "暂无描述",
      "language": null,
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Little100",
      "updatedAt": "2025-02-11T08:24:16Z",
      "createdAt": "2024-08-08T08:56:23Z",
      "topics": []
    },
    {
      "name": "Anvil_Fixer",
      "fullName": "Little100/Anvil_Fixer",
      "description": "can fix anvil in minecraft",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Anvil_Fixer",
      "updatedAt": "2025-02-04T10:45:07Z",
      "createdAt": "2024-12-01T08:08:41Z",
      "topics": []
    },
    {
      "name": "Player_Nekomusume",
      "fullName": "Little100/Player_Nekomusume",
      "description": "暂无描述",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Player_Nekomusume",
      "updatedAt": "2024-12-01T08:12:22Z",
      "createdAt": "2024-12-01T08:11:26Z",
      "topics": []
    },
    {
      "name": "Liteitemshow",
      "fullName": "Little100/Liteitemshow",
      "description": "暂无描述",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Liteitemshow",
      "updatedAt": "2024-12-01T08:05:56Z",
      "createdAt": "2024-08-31T06:30:45Z",
      "topics": []
    },
    {
      "name": "Minecraft_Player_Mating_Plugin",
      "fullName": "Little100/Minecraft_Player_Mating_Plugin",
      "description": "暂无描述",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Minecraft_Player_Mating_Plugin",
      "updatedAt": "2024-12-01T03:44:25Z",
      "createdAt": "2024-08-15T02:59:25Z",
      "topics": []
    },
    {
      "name": "Minecraft_Pack_Hub",
      "fullName": "Little100/Minecraft_Pack_Hub",
      "description": "暂无描述",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Minecraft_Pack_Hub",
      "updatedAt": "2024-09-09T15:16:17Z",
      "createdAt": "2024-05-27T16:15:42Z",
      "topics": []
    },
    {
      "name": "Namechecker",
      "fullName": "Little100/Namechecker",
      "description": "暂无描述",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Namechecker",
      "updatedAt": "2024-08-26T07:27:16Z",
      "createdAt": "2024-08-26T07:20:45Z",
      "topics": []
    },
    {
      "name": "GayMCPack_Extend",
      "fullName": "Little100/GayMCPack_Extend",
      "description": "GayMCPack Extend Pack",
      "language": null,
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/GayMCPack_Extend",
      "updatedAt": "2024-08-19T15:18:11Z",
      "createdAt": "2024-08-19T14:55:42Z",
      "topics": []
    },
    {
      "name": "Minecraft_Server_AutoBackUp",
      "fullName": "Little100/Minecraft_Server_AutoBackUp",
      "description": "For Minecraft Server Backup",
      "language": "Batchfile",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Minecraft_Server_AutoBackUp",
      "updatedAt": "2024-07-25T10:16:26Z",
      "createdAt": "2024-07-25T10:15:55Z",
      "topics": []
    },
    {
      "name": "Minecraft_AutoLauncher",
      "fullName": "Little100/Minecraft_AutoLauncher",
      "description": "暂无描述",
      "language": "Batchfile",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Minecraft_AutoLauncher",
      "updatedAt": "2024-07-19T05:27:07Z",
      "createdAt": "2024-07-09T16:54:38Z",
      "topics": []
    }
  ],
  "languages": {
    "JavaScript": 6,
    "Python": 3,
    "CSS": 4,
    "HTML": 57,
    "Java": 31
  }
};