window.GITHUB_DATA = {
  "projects": [
    {
      "name": "Minecraft_Online_Issues",
      "fullName": "Little100/Minecraft_Online_Issues",
      "description": "MOL 帮助玩家解决联机的疑难杂症",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Minecraft_Online_Issues",
      "updatedAt": "2026-02-19T02:37:52Z",
      "createdAt": "2025-05-16T11:53:06Z",
      "topics": []
    },
    {
      "name": "Web_Myself",
      "fullName": "Little100/Web_Myself",
      "description": "暂无描述",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Web_Myself",
      "updatedAt": "2026-02-19T01:11:03Z",
      "createdAt": "2025-09-06T14:20:55Z",
      "topics": []
    },
    {
      "name": "Minecraft-Resourcespack-Editor",
      "fullName": "Little100/Minecraft-Resourcespack-Editor",
      "description": "a minecraft resourcespack maker,can ez to make packs or edit pack for noob man",
      "language": "TypeScript",
      "stars": 28,
      "forks": 5,
      "url": "https://github.com/Little100/Minecraft-Resourcespack-Editor",
      "updatedAt": "2026-02-18T10:03:50Z",
      "createdAt": "2025-11-26T10:30:47Z",
      "topics": []
    },
    {
      "name": "AntiSeedMine",
      "fullName": "Little100/AntiSeedMine",
      "description": "暂无描述",
      "language": "Java",
      "stars": 1,
      "forks": 0,
      "url": "https://github.com/Little100/AntiSeedMine",
      "updatedAt": "2026-02-15T10:12:20Z",
      "createdAt": "2026-01-26T06:25:42Z",
      "topics": []
    },
    {
      "name": "theme-palette",
      "fullName": "Little100/theme-palette",
      "description": "暂无描述",
      "language": "CSS",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/theme-palette",
      "updatedAt": "2026-02-14T18:37:29Z",
      "createdAt": "2026-02-14T17:58:54Z",
      "topics": []
    },
    {
      "name": "Minecraft_Server_Manager",
      "fullName": "Little100/Minecraft_Server_Manager",
      "description": "a minecraft server mananger",
      "language": "JavaScript",
      "stars": 2,
      "forks": 0,
      "url": "https://github.com/Little100/Minecraft_Server_Manager",
      "updatedAt": "2026-02-14T03:03:17Z",
      "createdAt": "2025-01-22T09:39:23Z",
      "topics": []
    },
    {
      "name": "pluginmarket",
      "fullName": "Little100/pluginmarket",
      "description": "暂无描述",
      "language": "TypeScript",
      "stars": 3,
      "forks": 0,
      "url": "https://github.com/Little100/pluginmarket",
      "updatedAt": "2026-02-14T00:22:05Z",
      "createdAt": "2026-02-13T06:59:23Z",
      "topics": []
    },
    {
      "name": "MC_Skin_Generator",
      "fullName": "Little100/MC_Skin_Generator",
      "description": "Form a image to Minecaft skin",
      "language": "Python",
      "stars": 1,
      "forks": 0,
      "url": "https://github.com/Little100/MC_Skin_Generator",
      "updatedAt": "2026-02-11T06:21:25Z",
      "createdAt": "2025-05-04T06:33:05Z",
      "topics": []
    },
    {
      "name": "Little100",
      "fullName": "Little100/Little100",
      "description": "暂无描述",
      "language": null,
      "stars": 3,
      "forks": 0,
      "url": "https://github.com/Little100/Little100",
      "updatedAt": "2026-02-09T06:04:30Z",
      "createdAt": "2024-08-08T08:56:23Z",
      "topics": []
    },
    {
      "name": "mclanggeter",
      "fullName": "Little100/mclanggeter",
      "description": "暂无描述",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/mclanggeter",
      "updatedAt": "2026-02-05T05:15:22Z",
      "createdAt": "2026-02-05T05:15:09Z",
      "topics": []
    },
    {
      "name": "Avaritia_Plugin",
      "fullName": "Little100/Avaritia_Plugin",
      "description": "a simple plugin just from avaitia mod to plugin",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Avaritia_Plugin",
      "updatedAt": "2026-01-30T15:30:06Z",
      "createdAt": "2025-10-04T19:19:59Z",
      "topics": []
    },
    {
      "name": "docs",
      "fullName": "Little100/docs",
      "description": "docs",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/docs",
      "updatedAt": "2026-01-30T15:30:05Z",
      "createdAt": "2025-09-07T18:36:38Z",
      "topics": []
    },
    {
      "name": "ProjectE-plugin",
      "fullName": "Little100/ProjectE-plugin",
      "description": "A Minecraft Plugin,from ProjectE mod",
      "language": "Java",
      "stars": 15,
      "forks": 6,
      "url": "https://github.com/Little100/ProjectE-plugin",
      "updatedAt": "2026-01-30T15:30:04Z",
      "createdAt": "2025-07-27T11:20:55Z",
      "topics": [
        "minecraft",
        "minecraft-datapack",
        "minecraft-plugin",
        "minecraft-server",
        "projecte"
      ]
    },
    {
      "name": "Super_Farming",
      "fullName": "Little100/Super_Farming",
      "description": "a minecraft plugin ",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Super_Farming",
      "updatedAt": "2026-01-30T15:30:02Z",
      "createdAt": "2025-09-07T16:39:44Z",
      "topics": [
        "minecraft",
        "minecraft-plugin"
      ]
    },
    {
      "name": "Super_Stick_Sword",
      "fullName": "Little100/Super_Stick_Sword",
      "description": "A Minecraft Plugin,from Super Stick Sword mod",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Super_Stick_Sword",
      "updatedAt": "2026-01-30T15:30:01Z",
      "createdAt": "2025-09-07T03:03:33Z",
      "topics": [
        "minecraft",
        "minecraft-plugin"
      ]
    },
    {
      "name": "Anti-Recall-OneBot",
      "fullName": "Little100/Anti-Recall-OneBot",
      "description": "a normal antirecall",
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Anti-Recall-OneBot",
      "updatedAt": "2026-01-30T15:30:00Z",
      "createdAt": "2025-07-25T19:42:47Z",
      "topics": []
    },
    {
      "name": "MinecraftServersideBlockPack",
      "fullName": "Little100/MinecraftServersideBlockPack",
      "description": "一个可以在我的世界服务端显示方块贴图的方法",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/MinecraftServersideBlockPack",
      "updatedAt": "2026-01-30T15:30:00Z",
      "createdAt": "2025-08-11T12:57:37Z",
      "topics": []
    },
    {
      "name": "Other_Clear_Lag",
      "fullName": "Little100/Other_Clear_Lag",
      "description": "another minecraft clearlag plugin",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Other_Clear_Lag",
      "updatedAt": "2026-01-30T15:29:59Z",
      "createdAt": "2025-07-16T07:36:10Z",
      "topics": []
    },
    {
      "name": "Torcherino_Plugin",
      "fullName": "Little100/Torcherino_Plugin",
      "description": "我的世界加速火把 但是插件版",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Torcherino_Plugin",
      "updatedAt": "2026-01-30T15:29:57Z",
      "createdAt": "2025-07-07T15:49:57Z",
      "topics": []
    },
    {
      "name": "yayagongyi",
      "fullName": "Little100/yayagongyi",
      "description": "吖吖公益",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/yayagongyi",
      "updatedAt": "2026-01-30T15:29:56Z",
      "createdAt": "2025-04-19T02:18:12Z",
      "topics": []
    },
    {
      "name": "Video_Data_Analysis",
      "fullName": "Little100/Video_Data_Analysis",
      "description": "一个简单的分析视频平台的工具",
      "language": "Python",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Video_Data_Analysis",
      "updatedAt": "2026-01-30T15:29:56Z",
      "createdAt": "2025-06-28T12:50:02Z",
      "topics": []
    },
    {
      "name": "Furry.Beer",
      "fullName": "Little100/Furry.Beer",
      "description": "a furry html",
      "language": "JavaScript",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Furry.Beer",
      "updatedAt": "2026-01-30T15:29:54Z",
      "createdAt": "2025-06-27T17:16:21Z",
      "topics": [
        "furry"
      ]
    },
    {
      "name": "No_Eat_Limit",
      "fullName": "Little100/No_Eat_Limit",
      "description": "让玩家没有吃食物的饱食度限制",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/No_Eat_Limit",
      "updatedAt": "2026-01-30T15:29:52Z",
      "createdAt": "2025-04-13T08:37:31Z",
      "topics": []
    },
    {
      "name": "Alchemical_Bag_Plugin",
      "fullName": "Little100/Alchemical_Bag_Plugin",
      "description": "炼金术袋子 但是是插件版",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Alchemical_Bag_Plugin",
      "updatedAt": "2026-01-30T15:29:52Z",
      "createdAt": "2025-04-06T18:01:24Z",
      "topics": []
    },
    {
      "name": "Raw_Block_Smelting",
      "fullName": "Little100/Raw_Block_Smelting",
      "description": "Allows smelting raw ore blocks into metal blocks.",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Raw_Block_Smelting",
      "updatedAt": "2026-01-30T15:29:51Z",
      "createdAt": "2025-04-06T14:30:32Z",
      "topics": []
    },
    {
      "name": "GayMCPack",
      "fullName": "Little100/GayMCPack",
      "description": "a minecraft pack",
      "language": null,
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/GayMCPack",
      "updatedAt": "2026-01-30T15:29:48Z",
      "createdAt": "2024-08-19T14:52:11Z",
      "topics": []
    },
    {
      "name": ".love_domain",
      "fullName": "Little100/.love_domain",
      "description": "暂无描述",
      "language": "HTML",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/.love_domain",
      "updatedAt": "2026-01-30T15:29:47Z",
      "createdAt": "2025-02-11T08:08:17Z",
      "topics": []
    },
    {
      "name": "Player_Nekomusume",
      "fullName": "Little100/Player_Nekomusume",
      "description": "暂无描述",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Player_Nekomusume",
      "updatedAt": "2026-01-30T15:29:47Z",
      "createdAt": "2024-12-01T08:11:26Z",
      "topics": []
    },
    {
      "name": "Anvil_Fixer",
      "fullName": "Little100/Anvil_Fixer",
      "description": "can fix anvil in minecraft",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Anvil_Fixer",
      "updatedAt": "2026-01-30T15:29:46Z",
      "createdAt": "2024-12-01T08:08:41Z",
      "topics": []
    },
    {
      "name": "Minecraft_Player_Mating_Plugin",
      "fullName": "Little100/Minecraft_Player_Mating_Plugin",
      "description": "暂无描述",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Minecraft_Player_Mating_Plugin",
      "updatedAt": "2026-01-30T15:29:45Z",
      "createdAt": "2024-08-15T02:59:25Z",
      "topics": []
    },
    {
      "name": "Liteitemshow",
      "fullName": "Little100/Liteitemshow",
      "description": "暂无描述",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Liteitemshow",
      "updatedAt": "2026-01-30T15:29:45Z",
      "createdAt": "2024-08-31T06:30:45Z",
      "topics": []
    },
    {
      "name": "Namechecker",
      "fullName": "Little100/Namechecker",
      "description": "暂无描述",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Namechecker",
      "updatedAt": "2026-01-30T15:29:41Z",
      "createdAt": "2024-08-26T07:20:45Z",
      "topics": []
    },
    {
      "name": "GayMCPack_Extend",
      "fullName": "Little100/GayMCPack_Extend",
      "description": "GayMCPack Extend Pack",
      "language": null,
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/GayMCPack_Extend",
      "updatedAt": "2026-01-30T15:29:40Z",
      "createdAt": "2024-08-19T14:55:42Z",
      "topics": []
    },
    {
      "name": "Minecraft_Server_AutoBackUp",
      "fullName": "Little100/Minecraft_Server_AutoBackUp",
      "description": "For Minecraft Server Backup",
      "language": "Batchfile",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Minecraft_Server_AutoBackUp",
      "updatedAt": "2026-01-30T15:29:39Z",
      "createdAt": "2024-07-25T10:15:55Z",
      "topics": []
    },
    {
      "name": "Minecraft_AutoLauncher",
      "fullName": "Little100/Minecraft_AutoLauncher",
      "description": "暂无描述",
      "language": "Batchfile",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/Minecraft_AutoLauncher",
      "updatedAt": "2026-01-30T15:29:38Z",
      "createdAt": "2024-07-09T16:54:38Z",
      "topics": []
    },
    {
      "name": "Minecraft_Pack_Hub",
      "fullName": "Little100/Minecraft_Pack_Hub",
      "description": "暂无描述",
      "language": "JavaScript",
      "stars": 1,
      "forks": 0,
      "url": "https://github.com/Little100/Minecraft_Pack_Hub",
      "updatedAt": "2026-01-30T15:29:36Z",
      "createdAt": "2024-05-27T16:15:42Z",
      "topics": []
    },
    {
      "name": "ConstructionWand_Pugin",
      "fullName": "Little100/ConstructionWand_Pugin",
      "description": "a minecraft mod but reborn in spigot",
      "language": "Java",
      "stars": 1,
      "forks": 0,
      "url": "https://github.com/Little100/ConstructionWand_Pugin",
      "updatedAt": "2026-01-30T14:32:28Z",
      "createdAt": "2025-12-07T03:16:44Z",
      "topics": []
    },
    {
      "name": "CCB",
      "fullName": "Little100/CCB",
      "description": "暂无描述",
      "language": "Java",
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/CCB",
      "updatedAt": "2026-01-08T08:08:55Z",
      "createdAt": "2026-01-08T08:06:04Z",
      "topics": []
    },
    {
      "name": "DomMobsManager",
      "fullName": "Little100/DomMobsManager",
      "description": "暂无描述",
      "language": "Java",
      "stars": 1,
      "forks": 0,
      "url": "https://github.com/Little100/DomMobsManager",
      "updatedAt": "2025-12-19T15:47:25Z",
      "createdAt": "2025-12-08T06:39:54Z",
      "topics": []
    },
    {
      "name": "DomAreaPrvacyStatus",
      "fullName": "Little100/DomAreaPrvacyStatus",
      "description": "暂无描述",
      "language": "Java",
      "stars": 1,
      "forks": 0,
      "url": "https://github.com/Little100/DomAreaPrvacyStatus",
      "updatedAt": "2025-12-19T15:47:17Z",
      "createdAt": "2025-12-08T10:25:16Z",
      "topics": []
    },
    {
      "name": "DomAreaLimitComman",
      "fullName": "Little100/DomAreaLimitComman",
      "description": "暂无描述",
      "language": "Java",
      "stars": 1,
      "forks": 0,
      "url": "https://github.com/Little100/DomAreaLimitComman",
      "updatedAt": "2025-12-11T08:41:21Z",
      "createdAt": "2025-12-08T11:19:48Z",
      "topics": []
    },
    {
      "name": "MRE-Market",
      "fullName": "Little100/MRE-Market",
      "description": "a market,you can download some people's plugin or minecraft resourcepack",
      "language": null,
      "stars": 0,
      "forks": 0,
      "url": "https://github.com/Little100/MRE-Market",
      "updatedAt": "2025-12-08T13:49:15Z",
      "createdAt": "2025-12-06T06:18:49Z",
      "topics": []
    }
  ],
  "languages": {
    "HTML": 27,
    "CSS": 4,
    "JavaScript": 10,
    "Python": 1,
    "Vue": 12,
    "Rust": 4,
    "TypeScript": 21,
    "Java": 19,
    "Less": 1
  }
};